/**
 * The one lane table. Worktree creation and reset, each lane's gate, the scope check, the
 * AGENTS.md table and the CODEOWNERS lane rows read it; nothing else lists lanes.
 */
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { run } from './process.mjs';

/** Unit specs of the views lane that sit beside the workspace-ui specs, relative to `ui/`. */
const viewsUnitSpecs = ['catalog-schema.test.ts', 'json-render-roundtrip.test.tsx', 'layout.test.tsx',
  'mcp-apps-dispatch.test.tsx', 'mcp-apps-mime.test.ts', 'view-document-roundtrip.test.tsx'].map(name => `tests/unit/${name}`);

export const lanes = Object.freeze([
  { name: 'storage', branch: 'build/storage', kind: 'rust',
    directories: ['crates/storage/'], files: [], exclude: ['crates/storage/Cargo.toml'],
    crates: ['okf-jawn-storage'], features: ['okf-jawn-storage/runtime'], tests: [], testExclude: [],
    proves: 'store and index tests pass; rebuild never touches jobs, reviews or receipts' },
  { name: 'ingest', branch: 'build/ingest', kind: 'rust',
    directories: ['crates/ingest/'], files: [], exclude: ['crates/ingest/Cargo.toml'],
    crates: ['okf-jawn-ingest'], features: ['okf-jawn-ingest/runtime'], tests: [], testExclude: [],
    proves: 'converter and job-handler tests pass; crash/restart against the real RecordStore is a separate construction receipt' },
  { name: 'core-cli', branch: 'build/core-cli', kind: 'rust',
    directories: ['crates/core/', 'crates/cli/'], files: [], exclude: ['crates/core/Cargo.toml', 'crates/cli/Cargo.toml'],
    crates: ['okf-jawn-core', 'okf-jawn-cli'], features: [], tests: [], testExclude: [],
    proves: 'Application operations and the CLI command surface' },
  { name: 'server', branch: 'build/server', kind: 'rust',
    directories: ['crates/server/'], files: [], exclude: ['crates/server/Cargo.toml'],
    crates: ['okf-jawn-server'], features: ['okf-jawn-server/runtime'], tests: [], testExclude: [],
    proves: 'auth, session, sandbox-origin and readiness bindings' },
  { name: 'mcp-execution', branch: 'build/mcp-execution', kind: 'rust',
    directories: ['crates/mcp/'], files: [], exclude: ['crates/mcp/Cargo.toml'],
    crates: ['okf-jawn-mcp'], features: [], tests: [], testExclude: [],
    proves: 'tool and resource adapters; `bun scripts/dev.mjs qualify mcp-wire` against a running endpoint is a separate receipt' },
  { name: 'workspace-ui', branch: 'build/workspace-ui', kind: 'ui',
    directories: ['ui/'], files: [],
    exclude: ['ui/src/features/views/', 'ui/src/mcp-apps/', ...viewsUnitSpecs.map(spec => `ui/${spec}`), 'ui/package.json', 'ui/biome.json'],
    crates: [], features: [], tests: [], testExclude: ['src/features/views/**', 'src/mcp-apps/**', ...viewsUnitSpecs],
    proves: 'Explorer, WebMCP and sandbox-viewer unit results' },
  { name: 'views', branch: 'build/views', kind: 'ui',
    directories: ['ui/src/features/views/', 'ui/src/mcp-apps/'], files: viewsUnitSpecs.map(spec => `ui/${spec}`), exclude: [],
    crates: [], features: [], tests: ['src/features/views/', 'src/mcp-apps/', ...viewsUnitSpecs], testExclude: [],
    proves: 'View and MCP Apps unit results; the Apps bundle build and host rendering are separate qualifications' },
]);

export const LANE_TABLE_BEGIN = '<!-- lane-table:begin generated by `bun scripts/dev.mjs lanes-table` from scripts/lib/lanes.mjs; do not edit -->';
export const LANE_TABLE_END = '<!-- lane-table:end -->';

export function laneNamed(name) {
  const lane = lanes.find(entry => entry.name === name);
  if (!lane) throw new Error(`Unknown lane: ${name ?? '(none given)'}. Lanes: ${lanes.map(entry => entry.name).join(', ')}.`);
  return lane;
}

/** Where lane worktrees live: OKF_LANES_DIR, else D:\okf\lanes on Windows when D: exists, else ../okf-jawn-lanes. */
export function lanesParent(root, env = process.env, platform = process.platform, present = existsSync) {
  const configured = env.OKF_LANES_DIR?.trim();
  if (configured) return resolve(configured);
  if (platform === 'win32' && present('D:\\')) return 'D:\\okf\\lanes';
  return resolve(root, '..', 'okf-jawn-lanes');
}

/** Git in `cwd` with captured output. A non-zero exit is a result to inspect, never an exception. */
export function gitIn(cwd) {
  return (args, options = {}) => run('git', args, { cwd: options.cwd ?? cwd, capture: true, allowFailure: true });
}

/** The stdout of a git call that had to succeed. */
function must(result, what) {
  if (result.code !== 0) throw new Error(`${what} failed (git exit ${result.code}): ${result.stderr.trim()}`);
  return result.stdout;
}

const code = text => `\`${text}\``;

function owned(lane) {
  const paths = [...lane.directories, ...lane.files].map(code).join(', ');
  return lane.exclude.length ? `${paths} except ${lane.exclude.map(code).join(', ')}` : paths;
}

export function renderLaneTable() {
  return [
    '| Lane | Directories | Gate command | Expected receipt |',
    '| --- | --- | --- | --- |',
    '| integration-owner | `crates/contract`, `xtask`, `api/`, `generated/`, manifests, lockfiles, `scripts/`, `deploy/`, `tests/integration/` | `bun scripts/dev.mjs premerge` | `.artifacts/premerge/<sha>.log` ending `PASS premerge <sha>`: every CI step with all features, plus `check-receipts` |',
    ...lanes.map(lane => `| ${lane.name} | ${owned(lane)} | \`bun scripts/dev.mjs lane ${lane.name}\` | \`.artifacts/lane/${lane.name}/<sha>.log\` ending \`PASS ${lane.name} <sha>\`: ${lane.proves} |`),
  ].join('\n');
}

/** Rewrite the generated table between the markers in AGENTS.md. Returns whether the file changed. */
export async function syncLaneTable(root) {
  const path = join(root, 'AGENTS.md');
  const current = await readFile(path, 'utf8');
  const begin = current.indexOf(LANE_TABLE_BEGIN); const end = current.indexOf(LANE_TABLE_END);
  if (begin < 0 || end < begin) throw new Error('AGENTS.md has no lane-table markers; restore them before regenerating.');
  const next = `${current.slice(0, begin + LANE_TABLE_BEGIN.length)}\n${renderLaneTable()}\n${current.slice(end)}`;
  if (next === current) return false;
  await writeFile(path, next);
  return true;
}

/** Create `build/<lane>` worktrees from HEAD for the named lanes, or for all of them. */
export async function createLanes(root, { names = [], parent = lanesParent(root), git = gitIn(root) } = {}) {
  const selected = names.length ? names.map(laneNamed) : lanes;
  const status = await git(['status', '--porcelain']);
  if (status.code !== 0 || status.stdout.trim()) throw new Error('Commit the foundation before creating worktrees; no dirty-state fan-out.');
  const base = must(await git(['rev-parse', '--verify', 'HEAD']), 'git rev-parse HEAD').trim();
  await mkdir(parent, { recursive: true });
  const created = [];
  for (const lane of selected) {
    must(await git(['worktree', 'add', '-b', lane.branch, join(parent, lane.name), base]), `git worktree add ${lane.name}`);
    created.push(join(parent, lane.name));
  }
  return created;
}

/** Generated outputs any lane may commit after running `gen` (AGENTS.md, generator-input rule). */
export const generatedRoots = Object.freeze(['api/', 'generated/cli/', 'ui/src/api/generated/']);

/**
 * Stage 1 cure packages: temporary rows the integration owner adds per package and deletes when
 * Stage 1 closes. A `cure/*` branch without a row has no scope and fails the check.
 */
export const cures = Object.freeze([
  { name: 'gates', branch: 'cure/gates', base: 'integration/foundation-cure', paths: [
    'scripts/dev.mjs', 'scripts/lib/lanes.mjs', 'scripts/lib/receipts.mjs', 'scripts/lib/gates.mjs',
    'scripts/lib/process.mjs', 'scripts/lib/init.mjs', 'scripts/hooks/',
    'tests/foundation/fixture-repo.mjs', 'tests/foundation/lockfile.test.mjs', 'tests/foundation/lanes.test.mjs',
    'tests/foundation/receipts.test.mjs', 'tests/foundation/gates.test.mjs', 'tests/foundation/hooks.test.mjs',
    'tests/foundation/ci.test.mjs', 'tests/foundation/records.test.mjs', 'tests/foundation/policy.test.mjs',
    'tests/foundation/vendor.test.mjs', 'tests/foundation/process.test.mjs', 'tests/foundation/init.test.mjs',
    'tests/foundation/toolchain.test.mjs', 'tests/integration/acceptance.mjs',
    '.github/workflows/ci.yml', '.github/workflows/qualify.yml', '.github/workflows/contract.yml', '.github/CODEOWNERS',
    'Cargo.lock', 'crates/core/Cargo.toml', 'crates/storage/Cargo.toml', 'ui/vitest.config.ts',
    'README.md', 'AGENTS.md', 'justfile', 'verification.json', 'vendors.json', 'deploy/.env.example',
    'lefthook.yml', 'REPOSITORY-TREE.txt', '.cursor/plans/dependency_qualification_pass_e1c8326b.plan.md',
  ] },
]);

const inside = (path, entry) => (entry.endsWith('/') ? path.startsWith(entry) : path === entry);

export function scopeFor(branch) {
  const lane = lanes.find(entry => entry.branch === branch);
  if (lane) return { name: lane.name, base: 'main', allowed: [...lane.directories, ...lane.files, ...generatedRoots], exclude: lane.exclude };
  const cure = cures.find(entry => entry.branch === branch);
  return cure ? { name: cure.name, base: cure.base, allowed: cure.paths, exclude: [] } : null;
}

export function outOfScope(paths, scope) {
  return paths.filter(path => scope.exclude.some(entry => inside(path, entry)) || !scope.allowed.some(entry => inside(path, entry)));
}

/**
 * Fail when anything changed since the merge-base with the scope's base lies outside the scope.
 * Committed, staged, unstaged and untracked-but-not-ignored paths all count.
 */
export async function checkScope(root, { lane, base, git = gitIn(root) } = {}) {
  const branch = lane ? laneNamed(lane).branch : must(await git(['rev-parse', '--abbrev-ref', 'HEAD']), 'git rev-parse --abbrev-ref HEAD').trim();
  const scope = scopeFor(branch);
  if (!scope) throw new Error(`No scope row for branch ${branch}; add one to scripts/lib/lanes.mjs before pushing or gating it.`);
  const wanted = base ?? scope.base;
  let reference = null;
  for (const candidate of [wanted, `origin/${wanted}`]) {
    if ((await git(['rev-parse', '--verify', '--quiet', `${candidate}^{commit}`])).code === 0) { reference = candidate; break; }
  }
  if (!reference) throw new Error(`scope check needs ${wanted} or origin/${wanted} to compare against; neither exists here.`);
  const mergeBase = must(await git(['merge-base', 'HEAD', reference]), `git merge-base HEAD ${reference}`).trim();
  const tracked = must(await git(['diff', '--name-only', '--no-renames', '-z', mergeBase]), 'git diff --name-only');
  const untracked = must(await git(['ls-files', '--others', '--exclude-standard', '-z']), 'git ls-files --others');
  const changed = [...new Set([...tracked.split('\0'), ...untracked.split('\0')].filter(Boolean))].sort();
  const outside = outOfScope(changed, scope);
  if (outside.length) throw new Error(`scope check failed for ${scope.name}: ${outside.length} path(s) outside its scope:\n  ${outside.join('\n  ')}`);
  return { name: scope.name, base: mergeBase, changed };
}
