/**
 * The one lane table. Worktree creation and reset, each lane's gate, the scope check, the
 * AGENTS.md table and the CODEOWNERS lane rows read it; nothing else lists lanes.
 */
import { existsSync, realpathSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { run } from './process.mjs';
import { exists } from './files.mjs';

/** Unit specs of the views lane that sit beside the workspace-ui specs, relative to `ui/`. */
const viewsUnitSpecs = ['catalog-schema.test.ts', 'json-render-roundtrip.test.tsx', 'layout.test.tsx',
  'mcp-apps-dispatch.test.tsx', 'mcp-apps-mime.test.ts', 'view-document-roundtrip.test.tsx'].map(name => `tests/unit/${name}`);

export const lanes = Object.freeze([
  { name: 'storage', branch: 'build/storage', kind: 'rust',
    directories: ['crates/storage/'], files: [], exclude: ['crates/storage/Cargo.toml'],
    crates: ['okf-jawn-storage'], features: ['okf-jawn-storage/runtime'], tests: [], testExclude: [],
    proves: 'store and index tests pass; rebuild never touches jobs, reviews or receipts' },
  { name: 'ingest', branch: 'build/ingest', kind: 'rust',
    directories: ['crates/ingest/'], files: [], exclude: ['crates/ingest/Cargo.toml'],
    crates: ['okf-jawn-ingest'], features: ['okf-jawn-ingest/runtime'], tests: [], testExclude: [],
    proves: 'converter and job-handler tests pass; crash/restart against the real RecordStore is a separate construction receipt' },
  { name: 'core-cli', branch: 'build/core-cli', kind: 'rust',
    directories: ['crates/core/', 'crates/cli/'], files: [], exclude: ['crates/core/Cargo.toml', 'crates/cli/Cargo.toml'],
    crates: ['okf-jawn-core', 'okf-jawn-cli'], features: [], tests: [], testExclude: [],
    proves: 'Application operations and the CLI command surface' },
  { name: 'server', branch: 'build/server', kind: 'rust',
    directories: ['crates/server/'], files: [], exclude: ['crates/server/Cargo.toml'],
    crates: ['okf-jawn-server'], features: ['okf-jawn-server/runtime'], tests: [], testExclude: [],
    proves: 'auth, session, sandbox-origin and readiness bindings' },
  { name: 'mcp-execution', branch: 'build/mcp-execution', kind: 'rust',
    directories: ['crates/mcp/'], files: [], exclude: ['crates/mcp/Cargo.toml'],
    crates: ['okf-jawn-mcp'], features: [], tests: [], testExclude: [],
    proves: 'tool and resource adapters; `bun scripts/dev.mjs qualify mcp-wire` against a running endpoint is a separate receipt' },
  { name: 'workspace-ui', branch: 'build/workspace-ui', kind: 'ui',
    directories: ['ui/'], files: [],
    exclude: ['ui/src/features/views/', 'ui/src/mcp-apps/', ...viewsUnitSpecs.map(spec => `ui/${spec}`), 'ui/package.json', 'ui/biome.json'],
    crates: [], features: [], tests: [], testExclude: ['src/features/views/**', 'src/mcp-apps/**', ...viewsUnitSpecs],
    proves: 'Explorer, WebMCP and sandbox-viewer unit results' },
  { name: 'views', branch: 'build/views', kind: 'ui',
    directories: ['ui/src/features/views/', 'ui/src/mcp-apps/'], files: viewsUnitSpecs.map(spec => `ui/${spec}`), exclude: [],
    crates: [], features: [], tests: ['src/features/views/', 'src/mcp-apps/', ...viewsUnitSpecs], testExclude: [],
    proves: 'View and MCP Apps unit results; the Apps bundle build and host rendering are separate qualifications' },
]);

export const LANE_TABLE_BEGIN = '<!-- lane-table:begin generated by `bun scripts/dev.mjs lanes-table` from scripts/lib/lanes.mjs; do not edit -->';
export const LANE_TABLE_END = '<!-- lane-table:end -->';

export function laneNamed(name) {
  const lane = lanes.find(entry => entry.name === name);
  if (!lane) throw new Error(`Unknown lane: ${name ?? '(none given)'}. Lanes: ${lanes.map(entry => entry.name).join(', ')}.`);
  return lane;
}

/** Where lane worktrees live: OKF_LANES_DIR, else D:\okf\lanes on Windows when D: exists, else ../okf-jawn-lanes. */
export function lanesParent(root, env = process.env, platform = process.platform, present = existsSync) {
  const configured = env.OKF_LANES_DIR?.trim();
  if (configured) return resolve(configured);
  if (platform === 'win32' && present('D:\\')) return 'D:\\okf\\lanes';
  return resolve(root, '..', 'okf-jawn-lanes');
}

/** Git in `cwd` with captured output. A non-zero exit is a result to inspect, never an exception. */
export function gitIn(cwd) {
  return (args, options = {}) => run('git', args, { cwd: options.cwd ?? cwd, capture: true, allowFailure: true });
}

/** The stdout of a git call that had to succeed. */
function must(result, what) {
  if (result.code !== 0) throw new Error(`${what} failed (git exit ${result.code}): ${result.stderr.trim()}`);
  return result.stdout;
}

const code = text => `\`${text}\``;

function owned(lane) {
  const paths = [...lane.directories, ...lane.files].map(code).join(', ');
  return lane.exclude.length ? `${paths} except ${lane.exclude.map(code).join(', ')}` : paths;
}

export function renderLaneTable() {
  return [
    '| Lane | Directories | Gate command | Expected receipt |',
    '| --- | --- | --- | --- |',
    '| integration-owner | `crates/contract`, `xtask`, `api/`, `generated/`, manifests, lockfiles, `scripts/`, `deploy/`, `tests/integration/` | `bun scripts/dev.mjs premerge` | `.artifacts/premerge/<sha>.log` ending `PASS premerge <sha>`: every CI step with all features, plus `check-receipts` |',
    ...lanes.map(lane => `| ${lane.name} | ${owned(lane)} | \`bun scripts/dev.mjs lane ${lane.name}\` | \`.artifacts/lane/${lane.name}/<sha>.log\` ending \`PASS ${lane.name} <sha>\`: ${lane.proves} |`),
  ].join('\n');
}

/** Rewrite the generated table between the markers in AGENTS.md. Returns whether the file changed. */
export async function syncLaneTable(root) {
  const path = join(root, 'AGENTS.md');
  const current = await readFile(path, 'utf8');
  const begin = current.indexOf(LANE_TABLE_BEGIN); const end = current.indexOf(LANE_TABLE_END);
  if (begin < 0 || end < begin) throw new Error('AGENTS.md has no lane-table markers; restore them before regenerating.');
  const next = `${current.slice(0, begin + LANE_TABLE_BEGIN.length)}\n${renderLaneTable()}\n${current.slice(end)}`;
  if (next === current) return false;
  await writeFile(path, next);
  return true;
}

/** Create `build/<lane>` worktrees from HEAD for the named lanes, or for all of them. */
export async function createLanes(root, { names = [], parent = lanesParent(root), git = gitIn(root) } = {}) {
  const selected = names.length ? names.map(laneNamed) : lanes;
  const status = await git(['status', '--porcelain']);
  if (status.code !== 0 || status.stdout.trim()) throw new Error('Commit the foundation before creating worktrees; no dirty-state fan-out.');
  const base = must(await git(['rev-parse', '--verify', 'HEAD']), 'git rev-parse HEAD').trim();
  await mkdir(parent, { recursive: true });
  const created = [];
  for (const lane of selected) {
    must(await git(['worktree', 'add', '-b', lane.branch, join(parent, lane.name), base]), `git worktree add ${lane.name}`);
    created.push(join(parent, lane.name));
  }
  return created;
}

/** Generated outputs any lane may commit after running `gen` (AGENTS.md, generator-input rule). */
export const generatedRoots = Object.freeze(['api/', 'generated/cli/', 'ui/src/api/generated/']);

const inside = (path, entry) => (entry.endsWith('/') ? path.startsWith(entry) : path === entry);

export function scopeFor(branch) {
  const lane = lanes.find(entry => entry.branch === branch);
  if (lane) return { name: lane.name, base: 'main', allowed: [...lane.directories, ...lane.files, ...generatedRoots], exclude: lane.exclude };
  return null;
}

export function outOfScope(paths, scope) {
  return paths.filter(path => scope.exclude.some(entry => inside(path, entry)) || !scope.allowed.some(entry => inside(path, entry)));
}

/**
 * Fail when anything changed since the merge-base with the scope's base lies outside the scope.
 * Committed, staged, unstaged and untracked-but-not-ignored paths all count. With `head` (a
 * commit, as a pre-push hook receives it) only that commit's history counts and the working
 * tree is ignored.
 */
export async function checkScope(root, { lane, base, head, git = gitIn(root) } = {}) {
  const branch = lane ? laneNamed(lane).branch : must(await git(['rev-parse', '--abbrev-ref', 'HEAD']), 'git rev-parse --abbrev-ref HEAD').trim();
  if (branch === 'HEAD') throw new Error('scope: a detached HEAD names no lane; pass a lane: scope <lane>.');
  const scope = scopeFor(branch);
  if (!scope) throw new Error(`No scope row for branch ${branch}; add one to scripts/lib/lanes.mjs before pushing or gating it.`);
  const wanted = base ?? scope.base;
  let reference = null;
  for (const candidate of [wanted, `origin/${wanted}`]) {
    if ((await git(['rev-parse', '--verify', '--quiet', `${candidate}^{commit}`])).code === 0) { reference = candidate; break; }
  }
  if (!reference) throw new Error(`scope check needs ${wanted} or origin/${wanted} to compare against; neither exists here.`);
  const tip = head ?? 'HEAD';
  const mergeBase = must(await git(['merge-base', tip, reference]), `git merge-base ${tip} ${reference}`).trim();
  const tracked = must(await git(['diff', '--name-only', '--no-renames', '-z', mergeBase, ...(head ? [head] : [])]), 'git diff --name-only');
  const untracked = head ? '' : must(await git(['ls-files', '--others', '--exclude-standard', '-z']), 'git ls-files --others');
  const changed = [...new Set([...tracked.split('\0'), ...untracked.split('\0')].filter(Boolean))].sort();
  const outside = outOfScope(changed, scope);
  if (outside.length) throw new Error(`scope check failed for ${scope.name}: ${outside.length} path(s) outside its scope:\n  ${outside.join('\n  ')}`);
  return { name: scope.name, base: mergeBase, changed };
}

/** A path as the filesystem spells it, so git's and Node's spellings of one directory compare equal. */
function canonical(path) {
  let real;
  try { real = realpathSync.native(path); } catch { real = resolve(path); }
  return process.platform === 'win32' ? real.toLowerCase() : real;
}

/** Registered worktrees as {path, head, branch}; `branch` is null when detached. */
async function worktrees(git) {
  return must(await git(['worktree', 'list', '--porcelain']), 'git worktree list').split(/\r?\n\r?\n/)
    .map(block => block.trim()).filter(Boolean).map(block => ({
      path: /^worktree (.+)$/m.exec(block)?.[1] ?? '',
      head: /^HEAD ([0-9a-f]{40})$/m.exec(block)?.[1] ?? null,
      branch: /^branch (.+)$/m.exec(block)?.[1] ?? null,
    }));
}

/**
 * Remove lane worktrees and branches that hold nothing. Every lane directory that exists is
 * inspected whatever it has checked out; any doubt is a refusal, and a refusal removes nothing.
 */
export async function resetLanes(root, { parent = lanesParent(root), git = gitIn(root) } = {}) {
  const registered = await worktrees(git);
  const head = must(await git(['rev-parse', '--verify', 'HEAD']), 'git rev-parse HEAD').trim();
  const main = canonical(root);
  const targets = new Map();
  const branches = [];
  for (const lane of lanes) {
    for (const entry of registered) {
      if (entry.branch === `refs/heads/${lane.branch}` && canonical(entry.path) !== main) targets.set(canonical(entry.path), { path: entry.path, entry });
    }
    const expected = join(parent, lane.name);
    if (await exists(expected) && !targets.has(canonical(expected))) {
      targets.set(canonical(expected), { path: expected, entry: registered.find(entry => canonical(entry.path) === canonical(expected)) ?? null });
    }
    if ((await git(['rev-parse', '--verify', '--quiet', `refs/heads/${lane.branch}`])).code === 0) branches.push(lane.branch);
  }
  const refusals = [];
  const holdsWork = async (tip, label) => {
    const count = await git(['rev-list', '--count', `${head}..${tip}`]);
    if (count.code !== 0) return `${label}: could not compare it with HEAD (git exit ${count.code}); treated as holding work`;
    return Number(count.stdout.trim()) > 0 ? `${label} has ${count.stdout.trim()} commit(s) that are not in HEAD` : null;
  };
  for (const { path, entry } of targets.values()) {
    if (!entry) { refusals.push(`${path} exists but is not a worktree of this repository`); continue; }
    if (!await exists(path)) { refusals.push(`${path} is a registered worktree whose directory is missing; run \`git worktree prune\` and retry`); continue; }
    const status = await git(['status', '--porcelain'], { cwd: path });
    if (status.code !== 0) { refusals.push(`${path}: could not read its status (git exit ${status.code}); treated as dirty`); continue; }
    if (status.stdout.trim()) { refusals.push(`${path} is dirty`); continue; }
    const problem = entry.head ? await holdsWork(entry.head, path) : `${path} has no readable HEAD; treated as holding work`;
    if (problem) refusals.push(problem);
  }
  for (const branch of branches) {
    const problem = await holdsWork(`refs/heads/${branch}`, branch);
    if (problem) refusals.push(problem);
  }
  if (refusals.length) throw new Error(`lanes-reset refused; nothing was removed:\n  ${[...new Set(refusals)].join('\n  ')}`);
  for (const { path } of targets.values()) must(await git(['worktree', 'remove', path]), `git worktree remove ${path}`);
  for (const branch of branches) must(await git(['branch', '-d', branch]), `git branch -d ${branch}`);
  return `lanes-reset: removed ${targets.size} worktree(s) and ${branches.length} branch(es); nothing was forced.`;
}
