//! The converter crates Cargo.lock resolves, written as `generated/converter/packages.json`.
//!
//! A digest's `ConverterIdentity::packages` names the `docling`, `docling-core`,
//! `docling-onnx` and `docling-pdf` crates exactly as Cargo.lock pins them (name, version,
//! source), so a patched fork is visible. Ingest embeds this file; because it is generated
//! from the lock, gen-check fails when Cargo.lock changes and the file does not. Cargo.lock
//! is read line by line, the way `qualification/docling/lib/build.mjs` reads it for the
//! Docling receipt: only `[[package]]` tables and their `key = "value"` lines are used.

use std::collections::BTreeMap;
use std::error::Error;
use std::path::{Path, PathBuf};

use okf_jawn_contract::extraction::ConverterPackage;

use crate::output::write_json;

/// The crates that together are the converter, in the order the file lists them.
const CONVERTER_CRATES: [&str; 4] = ["docling", "docling-core", "docling-onnx", "docling-pdf"];

/// Write `packages.json` into `directory` from the workspace's Cargo.lock.
pub(crate) fn generate(directory: &Path) -> Result<(), Box<dyn Error>> {
    let lock = std::fs::read_to_string(lockfile())?;
    let packages = converter_packages(&lock)?;
    write_json(
        &directory.join("packages.json"),
        &serde_json::to_value(packages)?,
    )
}

/// The workspace lockfile, found from this crate's manifest rather than the working directory.
fn lockfile() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("Cargo.lock")
}

/// The converter crates of a Cargo.lock text, in `CONVERTER_CRATES` order.
///
/// Fails when a converter crate is missing, pinned more than once, or lacks a version or a
/// source: the identity would then be ambiguous or would not say where the crate came from.
fn converter_packages(lock: &str) -> Result<Vec<ConverterPackage>, Box<dyn Error>> {
    let mut found: BTreeMap<String, ConverterPackage> = BTreeMap::new();
    for table in package_tables(lock) {
        let Some(name) = table.get("name") else {
            continue;
        };
        if !CONVERTER_CRATES.contains(&name.as_str()) {
            continue;
        }
        let field = |key: &str| {
            table
                .get(key)
                .cloned()
                .ok_or_else(|| format!("Cargo.lock entry {name} has no {key}"))
        };
        let package = ConverterPackage {
            name: name.clone(),
            version: field("version")?,
            source: field("source")?,
        };
        if found.insert(name.clone(), package).is_some() {
            return Err(format!(
                "Cargo.lock pins {name} more than once; the converter identity would be ambiguous"
            )
            .into());
        }
    }
    CONVERTER_CRATES
        .iter()
        .map(|name| {
            found
                .remove(*name)
                .ok_or_else(|| format!("Cargo.lock does not pin the converter crate {name}").into())
        })
        .collect()
}

/// Every `[[package]]` table of a Cargo.lock text as its quoted `key = "value"` lines.
fn package_tables(lock: &str) -> Vec<BTreeMap<String, String>> {
    let mut tables = Vec::new();
    let mut current: Option<BTreeMap<String, String>> = None;
    for line in lock.lines() {
        if line.starts_with('[') {
            tables.extend(current.take());
            if line == "[[package]]" {
                current = Some(BTreeMap::new());
            }
            continue;
        }
        if let Some(table) = current.as_mut()
            && let Some((key, value)) = line.split_once(" = ")
            && let Some(value) = value
                .strip_prefix('"')
                .and_then(|rest| rest.strip_suffix('"'))
        {
            table.insert(key.to_owned(), value.to_owned());
        }
    }
    tables.extend(current);
    tables
}

#[cfg(test)]
mod tests {
    use std::error::Error;

    use super::{converter_packages, lockfile};

    type TestResult = Result<(), Box<dyn Error>>;

    const FORK: &str = "git+https://github.com/Heyoub/docling.rs?rev=e500c23#e500c23";

    fn entry(name: &str, version: &str, source: &str) -> String {
        format!(
            "[[package]]\nname = \"{name}\"\nversion = \"{version}\"\nsource = \"{source}\"\ndependencies = [\n \"serde\",\n]\n\n"
        )
    }

    fn lock(names: &[&str]) -> String {
        let mut text =
            "# This file is automatically @generated by Cargo.\nversion = 4\n\n".to_owned();
        text.push_str(&entry(
            "anyhow",
            "1.0.0",
            "registry+https://github.com/rust-lang/crates.io-index",
        ));
        for name in names {
            let (version, source) = if *name == "docling" {
                (
                    "1.93.5",
                    "registry+https://github.com/rust-lang/crates.io-index",
                )
            } else {
                ("1.93.6", FORK)
            };
            text.push_str(&entry(name, version, source));
        }
        text.push_str("[[package]]\nname = \"okf-jawn-contract\"\nversion = \"0.1.0\"\n");
        text
    }

    #[test]
    fn the_converter_is_the_four_docling_crates_as_the_lock_pins_them() -> TestResult {
        let packages = converter_packages(&lock(&[
            "docling-pdf",
            "docling",
            "docling-onnx",
            "docling-core",
        ]))?;
        let names: Vec<&str> = packages
            .iter()
            .map(|package| package.name.as_str())
            .collect();
        assert_eq!(
            names,
            ["docling", "docling-core", "docling-onnx", "docling-pdf"]
        );
        let pdf = packages.last().ok_or("docling-pdf")?;
        assert_eq!(pdf.version, "1.93.6");
        assert_eq!(pdf.source, FORK);
        Ok(())
    }

    #[test]
    fn a_missing_or_repeated_converter_crate_is_refused() {
        let missing = converter_packages(&lock(&["docling", "docling-core", "docling-pdf"]));
        assert!(
            matches!(&missing, Err(error) if error.to_string().contains("docling-onnx")),
            "{missing:?}"
        );
        let repeated = converter_packages(&lock(&[
            "docling",
            "docling-core",
            "docling-onnx",
            "docling-pdf",
            "docling-pdf",
        ]));
        assert!(
            matches!(&repeated, Err(error) if error.to_string().contains("more than once")),
            "{repeated:?}"
        );
    }

    #[test]
    fn a_crlf_lock_reads_the_same() -> TestResult {
        let text = lock(&["docling", "docling-core", "docling-onnx", "docling-pdf"]);
        let crlf = text.replace('\n', "\r\n");
        assert_eq!(converter_packages(&crlf)?, converter_packages(&text)?);
        Ok(())
    }

    #[test]
    fn the_workspace_lock_names_every_converter_crate_with_its_source() -> TestResult {
        let packages = converter_packages(&std::fs::read_to_string(lockfile())?)?;
        assert_eq!(packages.len(), 4);
        for package in &packages {
            assert!(
                package.source.starts_with("registry+") || package.source.starts_with("git+"),
                "{package:?}"
            );
        }
        Ok(())
    }
}
