//! Canonical operation declarations consumed by Rust and generated interface adapters.
//!
//! Every entry is an application operation, not a handler stub or a second schema language.
//! Every `$request` implements `scope::RequestScope`; `metadata` enforces that at compile time.
//!
//! Columns, in order: id, request type, response type, HTTP path, UI label, agent tool alias
//! (empty: not an MCP tool), operator and CLI alias (empty: none), tool visibility (`model`,
//! `app` or empty), minimum permission, MCP App presentation key, HTTP success status,
//! destructive hint, description. The `permission` column is the minimum capability;
//! `create_confirmation` requires a stronger, action-specific one through its `targets()`.

/// Expand the complete typed operation table into an adapter-specific consumer.
#[macro_export]
macro_rules! for_each_operation {
    ($consumer:ident) => {
        $consumer! {
            (list_workspaces, $crate::workspace::ListWorkspacesRequest, $crate::workspace::ListWorkspacesResponse, "/api/workspaces/list-workspaces", "Workspaces", "workspaces", "", "model", Read, "", 200, false, "List the workspaces this connection may read, each with its current head revision. Treat head as a pin: pass it to later reads as at = {\"kind\": \"revision\", \"revision\": head} so every call sees one consistent state, and compare it with a later listing to detect change."),
            (create_workspace, $crate::workspace::CreateWorkspaceRequest, $crate::workspace::Workspace, "/api/workspaces/create-workspace", "New workspace", "", "", "", Admin, "", 200, false, "Create a blank workspace; no example content is inserted."),
            (open_workspace, $crate::workspace::OpenWorkspaceRequest, $crate::workspace::Workspace, "/api/workspaces/open-workspace", "Open", "", "", "", Read, "", 200, false, "Open an existing authorized workspace."),
            (update_workspace, $crate::workspace::UpdateWorkspaceRequest, $crate::common::MutationResult, "/api/workspaces/update-workspace", "Properties", "", "", "", Write, "", 200, false, "Update workspace metadata at the supplied base revision."),
            (archive_workspace, $crate::workspace::ArchiveWorkspaceRequest, $crate::common::MutationResult, "/api/workspaces/archive-workspace", "Archive", "", "", "", Admin, "", 200, true, "Archive without deleting historical content."),
            (export_workspace, $crate::workspace::ExportWorkspaceRequest, $crate::import::Job, "/api/workspaces/export-workspace", "Export", "", "export", "", Write, "", 202, false, "Build a portable export with resolvable referenced assets."),
            (backup_workspace, $crate::workspace::BackupWorkspaceRequest, $crate::import::Job, "/api/workspaces/backup-workspace", "Backup", "", "", "", Admin, "", 202, false, "Back up content and durable application records."),
            (restore_workspace, $crate::workspace::RestoreWorkspaceRequest, $crate::import::Job, "/api/workspaces/restore-workspace", "Restore", "", "", "", Admin, "", 202, true, "Restore content and durable application records from a retained backup artifact."),
            (list_items, $crate::item::ListItemsRequest, $crate::item::ListItemsResponse, "/api/items/list-items", "Browse", "ls", "", "model", Read, "", 200, false, "List a folder with one-line descriptions at one resolved revision."),
            (get_item, $crate::item::GetItemRequest, $crate::item::ItemDocument, "/api/items/get-item", "Properties", "", "", "", Read, "", 200, false, "Read the editable Markdown and preserved properties of an item."),
            (create_item, $crate::item::CreateItemRequest, $crate::item::ItemDocument, "/api/items/create-item", "New note", "", "", "", Write, "", 200, false, "Create authored content without modifying source bytes."),
            (save_draft, $crate::item::SaveDraftRequest, $crate::item::Draft, "/api/items/save-draft", "Save", "", "", "", Write, "", 200, false, "Autosave the caller's own draft against its base revision; never creates a revision, and only a Snapshot commits it."),
            (list_drafts, $crate::item::ListDraftsRequest, $crate::item::ListDraftsResponse, "/api/items/list-drafts", "Drafts", "", "", "", Read, "", 200, false, "List only the caller's own uncommitted drafts."),
            (discard_draft, $crate::item::DiscardDraftRequest, $crate::item::Draft, "/api/items/discard-draft", "Discard draft", "", "", "", Write, "", 200, true, "Remove the caller's own draft without changing committed content."),
            (move_item, $crate::item::MoveItemRequest, $crate::common::MutationResult, "/api/items/move-item", "Move", "", "", "", Write, "", 200, false, "Move an item and rewrite references in one committed change."),
            (set_lifecycle, $crate::item::SetLifecycleRequest, $crate::common::MutationResult, "/api/items/set-lifecycle", "Archive", "", "", "", Write, "", 200, false, "Change lifecycle without approving any claim in the document."),
            (delete_item, $crate::item::DeleteItemRequest, $crate::common::MutationResult, "/api/items/delete-item", "Remove", "", "", "", Write, "", 200, true, "Remove the current reference while retaining historical source objects."),
            (create_folder, $crate::item::CreateFolderRequest, $crate::common::MutationResult, "/api/items/create-folder", "New folder", "", "", "", Write, "", 200, false, "Create a user-selected folder with a maintained index."),
            (list_types, $crate::item::ListTypesRequest, $crate::item::ListTypesResponse, "/api/types/list-types", "Types", "", "", "", Read, "", 200, false, "List built-in and user-defined OKF property schemas."),
            (set_type, $crate::item::SetTypeRequest, $crate::common::MutationResult, "/api/types/set-type", "Save type", "", "", "", Write, "", 200, false, "Persist a user-defined type without dropping extension properties."),
            (read_item, $crate::read::ReadItemRequest, $crate::read::ReadItemResponse, "/api/reads/read-item", "Read", "show", "", "model", Read, "source", 200, false, "Read an outline, Markdown, selected images, pages, or original. Resolve latest once; return exact citations and visible continuation."),
            (get_sources, $crate::source::GetSourcesRequest, $crate::source::GetSourcesResponse, "/api/reads/get-sources", "Sources", "sources", "", "model", Read, "source", 200, false, "Show supporting sources and occurrence-specific provenance."),
            (get_object, $crate::source::GetObjectRequest, $crate::source::GetObjectResponse, "/api/reads/get-object", "Original", "read_object", "", "app", Read, "", 200, false, "Return a bounded binary block authorized through its source; knowing a hash never grants access."),
            (create_sandbox_capability, $crate::read::CreateSandboxCapabilityRequest, $crate::read::SandboxCapability, "/api/reads/create-sandbox-capability", "Open sandboxed", "", "", "", Read, "", 200, false, "Mint a short-lived capability URL on the sandbox origin bound to one workspace, item, revision and representation; Explorer only."),
            (search_items, $crate::search::SearchRequest, $crate::search::SearchResponse, "/api/search/search-items", "Search", "grep", "", "model", Read, "", 200, false, "Search authorized content and return cited snippets, not whole-document dumps."),
            (get_links, $crate::search::GetLinksRequest, $crate::search::GetLinksResponse, "/api/search/get-links", "Links", "links", "", "model", Read, "", 200, false, "Read incoming or outgoing references at the selected revision."),
            (get_graph, $crate::search::GetGraphRequest, $crate::search::GetGraphResponse, "/api/search/get-graph", "Graph", "", "", "", Read, "", 200, false, "Read a bounded graph projection using the same authorized source identities."),
            (log_items, $crate::history::LogRequest, $crate::history::LogResponse, "/api/history/log-items", "Timeline", "log", "timeline", "model", Read, "timeline", 200, false, "Read content snapshots; Git history is not the complete application event log."),
            (diff_items, $crate::history::DiffRequest, $crate::history::DiffResponse, "/api/history/diff-items", "Changes", "diff", "changes", "model", Read, "changes", 200, false, "Compare two explicit versions and retain both references."),
            (commit_items, $crate::history::CommitRequest, $crate::common::MutationResult, "/api/history/commit-items", "Snapshot", "", "snapshot", "", Write, "", 200, false, "Name a snapshot from the caller's saved drafts; blocked only when a selected item was changed or deleted since its draft's base."),
            (restore_items, $crate::history::RestoreRequest, $crate::common::MutationResult, "/api/history/restore-items", "Rewind", "", "rewind", "", Write, "", 200, true, "Restore selected historical content as a new commit without rewriting history."),
            (blame_item, $crate::history::BlameRequest, $crate::history::BlameResponse, "/api/history/blame-item", "Who", "blame", "who", "model", Read, "", 200, false, "Show which commit last changed each selected line, not the origin of each fact."),
            (open_proposal, $crate::proposal::OpenProposalRequest, $crate::proposal::Proposal, "/api/proposals/open-proposal", "Propose", "propose", "", "model", Propose, "", 200, false, "Create a suggested change set without merging or marking anything reviewed."),
            (list_proposals, $crate::proposal::ListProposalsRequest, $crate::proposal::ListProposalsResponse, "/api/proposals/list-proposals", "Proposals", "", "", "", Read, "", 200, false, "List visible suggested changes."),
            (get_proposal, $crate::proposal::GetProposalRequest, $crate::proposal::Proposal, "/api/proposals/get-proposal", "Open proposal", "", "", "", Read, "", 200, false, "Read the exact proposed content and base revision."),
            (accept_proposal, $crate::proposal::AcceptProposalRequest, $crate::common::MutationResult, "/api/proposals/accept-proposal", "Approve", "", "approve", "", Approve, "", 200, false, "Accept exactly the confirmed proposal against the displayed head; never an agent tool."),
            (decline_proposal, $crate::proposal::DeclineProposalRequest, $crate::proposal::Proposal, "/api/proposals/decline-proposal", "Decline", "", "decline", "", Approve, "", 200, false, "Close a proposal without applying its content."),
            (add_comment, $crate::proposal::AddCommentRequest, $crate::proposal::Comment, "/api/proposals/add-comment", "Comment", "", "", "", Write, "", 200, false, "Add discussion without certifying content."),
            (create_confirmation, $crate::review::CreateConfirmationRequest, $crate::review::Confirmation, "/api/reviews/create-confirmation", "Confirm", "", "", "", Review, "", 200, false, "Create a session-bound confirmation for explicit human action; issuance is not review."),
            (create_review, $crate::review::CreateReviewRequest, $crate::review::Review, "/api/reviews/create-review", "Verify", "", "verify", "", Review, "", 200, false, "Record exact revision and content reviewed by an explicit authorized action; never infer review from OAuth identity."),
            (list_reviews, $crate::review::ListReviewsRequest, $crate::review::ListReviewsResponse, "/api/reviews/list-reviews", "Reviews", "", "", "", Read, "", 200, false, "Show review coverage and revisions without extending it to later edits."),
            (create_upload, $crate::import::CreateUploadRequest, $crate::import::Upload, "/api/imports/create-upload", "Add files", "", "", "", Write, "", 200, false, "Register a source occurrence before authenticated binary upload."),
            (complete_upload, $crate::import::CompleteUploadRequest, $crate::import::Upload, "/api/imports/complete-upload", "Finish upload", "", "", "", Write, "", 200, false, "Check expected bytes and digest before conversion."),
            (start_import, $crate::import::StartImportRequest, $crate::import::Job, "/api/imports/start-import", "Import", "", "import", "", Write, "", 202, false, "Durably register conversion and source creation, preserving originals."),
            (get_job, $crate::import::GetJobRequest, $crate::import::Job, "/api/imports/get-job", "Progress", "", "", "", Read, "", 200, false, "Read durable job progress; a receipt does not imply completion."),
            (list_jobs, $crate::import::ListJobsRequest, $crate::import::ListJobsResponse, "/api/imports/list-jobs", "Jobs", "", "", "", Read, "", 200, false, "List conversion, export, and maintenance work."),
            (retry_job, $crate::import::RetryJobRequest, $crate::import::Job, "/api/imports/retry-job", "Retry", "", "", "", Write, "", 202, false, "Retry the same durable work identity without duplicating completed effects."),
            (cancel_job, $crate::import::CancelJobRequest, $crate::import::Job, "/api/imports/cancel-job", "Cancel", "", "", "", Write, "", 200, false, "Cancel work while retaining completed uploads and recorded state."),
            (redigest_item, $crate::import::RedigestRequest, $crate::import::Job, "/api/imports/redigest-item", "Reconvert", "", "", "", Write, "", 202, false, "Re-run extraction with declared settings; preserve prior digests and separate corrections."),
            (correct_digest, $crate::import::CorrectDigestRequest, $crate::common::MutationResult, "/api/imports/correct-digest", "Correct text", "", "", "", Write, "", 200, false, "Save a correction separately from generated extraction."),
            (get_rules, $crate::conventions::GetRulesRequest, $crate::conventions::NamingRules, "/api/conventions/get-rules", "Conventions", "", "", "", Read, "", 200, false, "Read the same naming conventions used by the form, YAML editor, and import process."),
            (set_rules, $crate::conventions::SetRulesRequest, $crate::common::MutationResult, "/api/conventions/set-rules", "Save conventions", "", "", "", Write, "", 200, false, "Save explicit rules as versioned context."),
            (preview_names, $crate::conventions::PreviewNamesRequest, $crate::conventions::RenamePlan, "/api/conventions/preview-names", "Preview", "", "", "", Read, "", 200, false, "Compute before and after naming changes without mutating content."),
            (apply_names, $crate::conventions::ApplyNamesRequest, $crate::common::MutationResult, "/api/conventions/apply-names", "Apply", "", "", "", Write, "", 200, true, "Apply the checked preview and rewrite references in one versioned action."),
            (get_attention, $crate::attention::GetAttentionRequest, $crate::attention::GetAttentionResponse, "/api/attention/get-attention", "Attention", "", "attention", "", Read, "", 200, false, "Show actionable maintenance observations; an empty result is not a safety certificate."),
            (rebuild_index, $crate::attention::RebuildIndexRequest, $crate::import::Job, "/api/attention/rebuild-index", "Rebuild search", "", "", "", Admin, "", 202, false, "Rebuild only derived search and link data; preserve reviews and receipts."),
            (get_view, $crate::views::GetViewRequest, $crate::views::ViewDocument, "/api/views/get-view", "Open visual", "", "", "", Read, "", 200, false, "Read a saved visual artifact and its precise source bindings."),
            (present_view, $crate::views::PresentRequest, $crate::views::PresentResponse, "/api/views/present-view", "Present", "present", "", "model", Read, "present", 200, false, "Render a validated candidate using approved components and real source bindings; does not save or approve it."),
            (resolve_view, $crate::views::ResolveViewRequest, $crate::views::PresentResponse, "/api/views/resolve-view", "Refresh", "", "", "", Read, "", 200, false, "Resolve pinned inputs or explicitly refresh a live view without silently modifying saved state."),
            (export_view, $crate::views::ExportViewRequest, $crate::import::Job, "/api/views/export-view", "Export visual", "", "", "", Write, "", 202, false, "Export the spec, source references, data table and rendering."),
            (get_catalog, $crate::views::GetCatalogRequest, $crate::views::CatalogResponse, "/api/views/get-catalog", "Components", "catalog", "", "model", Read, "", 200, false, "Describe the allowed visual components; the catalog never grants capabilities."),
            (get_receipt, $crate::events::GetReceiptRequest, $crate::events::Receipt, "/api/events/get-receipt", "Tool results returned", "", "", "", Read, "", 200, false, "Inspect the exact sources returned through this server, not an external model internal state."),
            (list_events, $crate::events::ListEventsRequest, $crate::events::ListEventsResponse, "/api/events/list-events", "Activity", "", "", "", Read, "", 200, false, "Read resumable notifications without treating them as authoritative document content."),
            (get_session, $crate::common::Empty, $crate::access::SessionResponse, "/api/session/get-session", "Account", "", "", "", Read, "", 200, false, "Read the current authenticated principal without exposing credentials."),
            (create_connector, $crate::access::CreateConnectorRequest, $crate::access::IssuedConnector, "/api/session/create-connector", "Connect an agent", "", "", "", Admin, "", 200, false, "Issue a local MCP connector credential scoped to read, or read and propose; never review or approve. Local owner only; hosted agents use WorkOS Connect."),
            (list_connectors, $crate::access::ListConnectorsRequest, $crate::access::ListConnectorsResponse, "/api/session/list-connectors", "Connected agents", "", "", "", Admin, "", 200, false, "List local connector credentials and their scopes without secrets. Local owner only."),
            (revoke_connector, $crate::access::RevokeConnectorRequest, $crate::access::Connector, "/api/session/revoke-connector", "Disconnect", "", "", "", Admin, "", 200, true, "Revoke a local connector credential immediately. Local owner only."),
            (get_health, $crate::health::HealthRequest, $crate::health::HealthResponse, "/api/health/get-health", "Health", "", "", "", Read, "", 200, false, "Read process liveness, not feature qualification."),
            (get_readiness, $crate::health::ReadinessRequest, $crate::health::ReadinessResponse, "/api/health/get-readiness", "Readiness", "", "", "", Read, "", 200, false, "Read configured dependency readiness."),
        }
    };
}
