//! Conversion returns structural artifacts and locators while retaining original bytes.
//!
//! The port mirrors what the pinned Docling converter takes and returns: a per-document time
//! budget, typed settings, a structured document and a status. A document the converter cannot
//! read is a result whose status is `Unsupported` or `Failure`, never an error: the caller
//! records that state on the source card and keeps the bytes. An error means the worker itself
//! is at fault.

use std::path::PathBuf;
use std::time::Duration;

use okf_jawn_contract::{
    identity::Digest,
    read::{OutlineEntry, Selection},
};
use serde::{Deserialize, Serialize};

use crate::{ports::PortFuture, storage::LocalSource};

/// When optical character recognition runs.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OcrPolicy {
    /// Recognize only regions that have no embedded text layer.
    #[default]
    Auto,
    /// Never run recognition; layout and table structure are still detected.
    Skip,
    /// Recognize every page from its rendered image, ignoring an embedded text layer.
    ForceFullPage,
}

/// Explicit converter settings; they are part of the identity of the digest they produce.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ConversionSettings {
    /// When recognition runs.
    pub ocr: OcrPolicy,
    /// Recognition language, such as `en`; `None` uses the converter's default.
    pub ocr_language: Option<String>,
    /// Reconstruct table structure.
    pub table_structure: bool,
    /// Retain a rendered image of every page.
    pub page_images: bool,
}

/// One document to convert inside a bounded worker.
#[derive(Debug, Clone)]
pub struct ConversionInput {
    /// Verified retained original; its path has no file extension.
    pub source: LocalSource,
    /// Supplied occurrence filename; its extension selects the input format.
    pub file_name: String,
    /// Settings recorded with the result.
    pub settings: ConversionSettings,
    /// Time budget for this document. A converter that runs out returns what it finished with
    /// status `PartialSuccess`; the worker supervisor enforces the hard bound.
    pub timeout: Duration,
    /// New, empty directory controlled by the worker supervisor; every output is written here.
    pub output_directory: PathBuf,
}

/// One derivative generated by a converter, ready for the blob store.
#[derive(Debug, Clone)]
pub struct ConvertedAsset {
    /// File written beneath the output directory.
    pub path: PathBuf,
    /// Detected derivative media type.
    pub media_type: String,
    /// Page, cells, figure, or other original location.
    pub selection: Selection,
    /// Original or generated caption; the origin is not concealed.
    pub caption: Option<String>,
}

/// How a conversion ended.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConversionStatus {
    /// The whole document was converted.
    Success,
    /// A document was produced but is incomplete; `Conversion::issues` says why.
    PartialSuccess,
    /// No extractor exists for this format; the bytes are retained, nothing was extracted.
    Unsupported,
    /// The converter could not read the document; the bytes are retained.
    Failure,
}

/// One problem the converter recorded.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConversionIssue {
    /// Converter component that reported it.
    pub component: String,
    /// Stage that recorded it.
    pub module: String,
    /// What went wrong.
    pub message: String,
}

/// The converter that produced a result; part of the identity of the digest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConverterIdentity {
    /// Converter name, such as `docling`.
    pub name: String,
    /// Exact converter version.
    pub version: String,
}

/// What a successful or partial conversion extracted.
#[derive(Debug, Clone)]
pub struct ConvertedDocument {
    /// Structured Markdown.
    pub markdown: String,
    /// File beneath the output directory holding the converter's structured document as JSON.
    pub structured: PathBuf,
    /// Navigable source locations.
    pub outline: Vec<OutlineEntry>,
    /// Images, page renders, tables, and other retained assets.
    pub assets: Vec<ConvertedAsset>,
}

/// The outcome of converting one document; never a replacement for the original.
#[derive(Debug, Clone)]
pub struct Conversion {
    /// Identity of the original bytes.
    pub source_digest: Digest,
    /// Converter that ran.
    pub converter: ConverterIdentity,
    /// Settings that were applied.
    pub settings: ConversionSettings,
    /// How the conversion ended.
    pub status: ConversionStatus,
    /// The extraction; present exactly when the status is `Success` or `PartialSuccess`.
    pub document: Option<ConvertedDocument>,
    /// Problems the converter recorded; never empty for a partial, unsupported or failed result.
    pub issues: Vec<ConversionIssue>,
}

/// Bounded worker execution backed by the selected conversion library.
pub trait Converter: Send + Sync {
    /// Convert one document within its time budget.
    ///
    /// Dropping the returned future abandons the result; the worker supervisor owns
    /// cancellation and the memory bound.
    fn convert(&self, input: ConversionInput) -> PortFuture<'_, Conversion>;
}

impl Default for ConversionSettings {
    fn default() -> Self {
        Self {
            ocr: OcrPolicy::Auto,
            ocr_language: None,
            table_structure: true,
            page_images: false,
        }
    }
}
