//! Conversion returns structural artifacts and locators while retaining original bytes.
//!
//! The port mirrors what the pinned Docling converter takes and returns: a one-based page
//! window (docling `page_range`), a per-window time budget, typed settings, a structured
//! document and a status. A document the converter cannot read is a result whose status is
//! `Unsupported` or `Failure`, never an error: the caller records that state on the source card
//! and keeps the bytes. An error means the worker itself is at fault (a missing model or native
//! library included).
//!
//! Windows bound the worker's memory (Stage 1b design section 9.1). The loop over windows, the
//! merge into one `ConversionRecord` and the whole-document `PageCoverage::check` belong to
//! ingest's import and redigest handler; this module owns the shapes and the per-window check.
//!
//! `ConversionSettings`, `OcrPolicy`, `ConverterIdentity`, `ConverterIssue`, `FailureReason`
//! and `ExtractionWarning` are the contract's, so the wire, the job and the retained record
//! carry one definition of each.

use std::path::PathBuf;
use std::time::Duration;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use okf_jawn_contract::{
    common::{PageRange, TextRange},
    error::{ApiError, ErrorCode},
    extraction::{ConversionOutcome, ExtractionWarning},
    identity::Digest,
    read::{AssetRole, OutlineEntry},
    source::SourceLocation,
};

use crate::{ports::PortFuture, storage::LocalSource};

pub use okf_jawn_contract::extraction::{
    ConversionSettings, ConverterIdentity, ConverterIssue, FailureReason, OcrPolicy,
};

/// One window of one document to convert inside a bounded worker.
#[derive(Debug, Clone)]
pub struct ConversionInput {
    /// Verified retained original; its path has no file extension.
    pub source: LocalSource,
    /// Supplied occurrence filename; its extension selects the input format.
    pub file_name: String,
    /// Contract settings, recorded in the converter identity of the result.
    pub settings: ConversionSettings,
    /// One-based inclusive page window (docling `page_range`); `None` converts the whole
    /// document, which is the only choice for a format docling converts whole.
    pub window: Option<PageRange>,
    /// Time budget for this window. A converter that runs out returns what it finished with
    /// status `PartialSuccess`; the worker supervisor enforces the hard bound.
    pub timeout: Duration,
    /// New, empty directory controlled by the worker supervisor; every output is written here.
    pub output_directory: PathBuf,
}

/// The worker bounds, set from the whole-document versus windowed measurement
/// (`converter-worker-memory-ceiling`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConverterLimits {
    /// Pages per window.
    pub window_pages: u32,
    /// Hard memory cap of the child process, in bytes.
    pub memory_limit_bytes: u64,
}

/// One derivative generated by a converter, ready for the blob store.
#[derive(Debug, Clone, PartialEq)]
pub struct ConvertedAsset {
    /// File written beneath the output directory.
    pub path: PathBuf,
    /// Detected derivative media type.
    pub media_type: String,
    /// A page render or a picture's own image.
    pub role: AssetRole,
    /// Where in the original the asset is, and how that was obtained.
    pub location: SourceLocation,
    /// Pixel dimensions; present exactly when the asset is a raster image.
    pub pixel_size: Option<PixelSize>,
    /// The document's own caption or alternative text; `None` when it gives the asset none.
    pub caption: Option<String>,
}

/// A converted asset once retained: the blob digest in place of the worker's file.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct RetainedAsset {
    /// Digest of the retained bytes.
    pub digest: Digest,
    /// Detected derivative media type.
    pub media_type: String,
    /// A page render or a picture's own image.
    pub role: AssetRole,
    /// Where in the original the asset is, and how that was obtained.
    pub location: SourceLocation,
    /// Pixel dimensions; present exactly when the asset is a raster image.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pixel_size: Option<PixelSize>,
    /// The document's own caption or alternative text.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub caption: Option<String>,
}

/// Pixel dimensions of a raster image asset.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct PixelSize {
    /// Width in pixels.
    pub width: u32,
    /// Height in pixels.
    pub height: u32,
}

/// Docling's status, plus the application's states.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ConversionStatus {
    /// The whole window was converted.
    Success,
    /// A document was produced but is incomplete; `Conversion::issues` says why.
    PartialSuccess,
    /// No extractor exists for this format; the bytes are retained, nothing was extracted.
    Unsupported,
    /// No document was produced; the bytes are retained. A child that reached its memory cap
    /// is `Failure(FailureReason::MemoryLimit)`.
    Failure(FailureReason),
}

/// Coverage of one window: the three lists are ascending, disjoint and together cover exactly
/// `window`. `check` enforces it; the contract `PageCoverage::check` applies only to the
/// merged, whole-document coverage over `1..=page_count`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WindowCoverage {
    /// The window converted.
    pub window: PageRange,
    /// Pages converted with no known loss.
    pub converted: Vec<PageRange>,
    /// Pages converted whose text is partly undecodable.
    pub partly_extracted: Vec<PageRange>,
    /// Pages with no extraction.
    pub not_converted: Vec<PageRange>,
}

/// A line range of the converted Markdown and where it came from in the original.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct LineLocation {
    /// One-based inclusive lines of the Markdown.
    pub lines: TextRange,
    /// Where those lines are in the original, and how that was obtained.
    pub location: SourceLocation,
}

/// A table the converter recognised, kept for datasets (Stage 1b design section 9.5).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ConvertedTable {
    /// Lines of the Markdown that render it.
    pub lines: TextRange,
    /// Where the table is in the original.
    pub location: SourceLocation,
    /// Rows in the grid.
    pub num_rows: u32,
    /// Columns in the grid.
    pub num_cols: u32,
    /// Docling `table_cells`, at zero-based grid offsets.
    pub cells: Vec<ConvertedCell>,
}

/// One cell of a converted table.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ConvertedCell {
    /// Zero-based row offset.
    pub row: u32,
    /// Zero-based column offset.
    pub column: u32,
    /// Rows the cell spans, at least one.
    pub row_span: u32,
    /// Columns the cell spans, at least one.
    pub column_span: u32,
    /// The cell's text.
    pub text: String,
    /// Whether docling marked the cell a column header.
    pub column_header: bool,
    /// Whether docling marked the cell a row header.
    pub row_header: bool,
}

/// What a successful or partial conversion of one window extracted.
#[derive(Debug, Clone)]
pub struct ConvertedDocument {
    /// Structured Markdown.
    pub markdown: String,
    /// File beneath the output directory holding the docling JSON export of this window.
    pub structured: PathBuf,
    /// Navigable source locations, with lines relative to this window's Markdown. A heading
    /// entry selects its section as lines, from the heading line to the line before the next
    /// heading of the same or a higher level, or to the end of the text.
    pub outline: Vec<OutlineEntry>,
    /// Page renders and pictures.
    pub assets: Vec<ConvertedAsset>,
    /// Line-to-location map of `markdown`: ascending, non-overlapping line ranges.
    pub locations: Vec<LineLocation>,
    /// Tables, for datasets.
    pub tables: Vec<ConvertedTable>,
    /// What the converter or the worker noticed that the reader should know.
    pub warnings: Vec<ExtractionWarning>,
}

/// The outcome of converting one window; never a replacement for the original.
#[derive(Debug, Clone)]
pub struct Conversion {
    /// Identity of the original bytes.
    pub source_digest: Digest,
    /// Identity including settings, packages, hashed models and the window size.
    pub converter: ConverterIdentity,
    /// How the conversion ended.
    pub status: ConversionStatus,
    /// The extraction; present exactly when the status is `Success` or `PartialSuccess`.
    pub document: Option<ConvertedDocument>,
    /// For a windowed (paginated) conversion: what this window converted.
    pub coverage: Option<WindowCoverage>,
    /// Problems the converter recorded; never empty for a partial, unsupported or failed result.
    pub issues: Vec<ConverterIssue>,
}

/// The docling JSON export of one window, retained.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct WindowExport {
    /// The window; `None` when the document was converted whole.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub window: Option<PageRange>,
    /// Digest of the retained export.
    pub digest: Digest,
    /// The lines of the record's joined Markdown this window produced; `None` when the window
    /// produced no text. A redigest that converts only a source's unconverted pages replaces
    /// exactly these line ranges, and only under the same converter identity.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lines: Option<TextRange>,
}

/// The retained record a conversion digest names; JSON in the blob store, written by ingest
/// and read by core for citations (locations) and datasets (tables).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ConversionRecord {
    /// Identity including settings, packages, hashed models and the window size.
    pub converter: ConverterIdentity,
    /// The converter's verdict over the whole document.
    pub outcome: ConversionOutcome,
    /// Pages of a paginated original; absent for a format converted whole.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub page_count: Option<u32>,
    /// One docling export per converted window, in page order.
    pub structured: Vec<WindowExport>,
    /// SHA-256 of the Markdown the record describes.
    pub markdown: Digest,
    /// Line-to-location map of that Markdown.
    pub locations: Vec<LineLocation>,
    /// The outline of the Markdown the record describes, for the whole document: the window
    /// outlines joined, with lines in the joined Markdown. A heading entry selects its section
    /// as lines, from the heading line to the line before the next heading of the same or a
    /// higher level, or to the end of the text. It is what the `outline` read view serves for a
    /// converted source and the input of `reading::section_lines`.
    pub outline: Vec<OutlineEntry>,
    /// Tables, for datasets.
    pub tables: Vec<ConvertedTable>,
    /// Retained page renders and pictures.
    pub assets: Vec<RetainedAsset>,
    /// What the converter or the worker noticed that the reader should know.
    pub warnings: Vec<ExtractionWarning>,
}

/// Bounded worker execution backed by the selected conversion library.
pub trait Converter: Send + Sync {
    /// Page count of a paginated original (docling `pdf_page_count`; 1 for an image); `None`
    /// for a format converted whole. Read in the worker, from the retained bytes.
    fn page_count<'a>(
        &'a self,
        source: &'a LocalSource,
        file_name: &'a str,
    ) -> PortFuture<'a, Option<u32>>;

    /// Convert one window in a child process under `limits().memory_limit_bytes`.
    ///
    /// A document fault is a `Conversion` (cap reached: `Failure(MemoryLimit)`); a worker
    /// fault, including a missing model or native library, is an error. Dropping the future
    /// kills the child.
    fn convert(&self, input: ConversionInput) -> PortFuture<'_, Conversion>;

    /// The configured bounds.
    fn limits(&self) -> ConverterLimits;
}

impl WindowCoverage {
    /// Refuse a window that is not a page range, and lists that are not ascending, overlap,
    /// leave a page of the window uncovered, or reach outside it.
    ///
    /// # Errors
    /// Returns `Internal` whose field is a JSON Pointer, relative to the coverage, to the
    /// first range at fault: a converter that reports such coverage is a worker fault.
    pub fn check(&self) -> Result<(), ApiError> {
        if self.window.start == 0 || self.window.start > self.window.end {
            return Err(window_error(
                "a window runs from one page to a later one",
                "/window",
            ));
        }
        let lists: [(&str, &[PageRange]); 3] = [
            ("converted", &self.converted),
            ("partly_extracted", &self.partly_extracted),
            ("not_converted", &self.not_converted),
        ];
        let mut all: Vec<(&PageRange, String)> = Vec::new();
        for (name, ranges) in lists {
            let mut previous_end = 0_u32;
            for (index, range) in ranges.iter().enumerate() {
                let field = format!("/{name}/{index}");
                if range.start > range.end {
                    return Err(window_error(
                        "a page range runs from one page to a later one",
                        &field,
                    ));
                }
                if range.start < self.window.start || range.end > self.window.end {
                    return Err(window_error("a page range lies outside the window", &field));
                }
                if range.start <= previous_end {
                    return Err(window_error(
                        "page ranges of one list are ascending and do not overlap",
                        &field,
                    ));
                }
                previous_end = range.end;
                all.push((range, field));
            }
        }
        all.sort_by_key(|(range, _)| range.start);
        let mut next = self.window.start;
        for (range, field) in all {
            if range.start != next {
                let message = if range.start < next {
                    "the coverage lists overlap"
                } else {
                    "the coverage lists leave a page of the window uncovered"
                };
                return Err(window_error(message, &field));
            }
            next = range.end.saturating_add(1);
        }
        if next.checked_sub(1) == Some(self.window.end) {
            Ok(())
        } else {
            Err(window_error(
                "the coverage lists leave a page of the window uncovered",
                "/window",
            ))
        }
    }
}

fn window_error(message: &str, field: &str) -> ApiError {
    ApiError::new(ErrorCode::Internal, message).with_field(field)
}
