//! Conversion returns structural artifacts and locators while retaining original bytes.

use crate::{ports::PortFuture, storage::LocalSource};
use okf_jawn_contract::{
    common::Warning,
    identity::Digest,
    read::{OutlineEntry, Selection},
};
use std::collections::BTreeMap;
use std::path::PathBuf;

/// Explicit converter settings participate in the derivative cache key.
#[derive(Debug, Clone)]
pub struct ConversionRequest {
    /// Verified local original, materialized inside the worker's allowed directory.
    pub source: LocalSource,
    /// Exact converter version selected by the deployment.
    pub converter_version: String,
    /// Explicit settings, including extraction mode and OCR language when used.
    pub settings: BTreeMap<String, serde_json::Value>,
    /// New output directory controlled by the worker supervisor.
    pub output_directory: PathBuf,
}

/// One derivative generated by a converter, ready for ingestion into the object store.
#[derive(Debug, Clone)]
pub struct ConvertedAsset {
    /// File written beneath the controlled output directory.
    pub path: PathBuf,
    /// Detected derivative media type.
    pub media_type: String,
    /// Page, cells, figure, or other original location.
    pub selection: Selection,
    /// Original or generated caption; the origin is not concealed.
    pub caption: Option<String>,
}

/// Structured extraction with warnings, never an authoritative replacement for the original.
#[derive(Debug, Clone)]
pub struct ConversionResult {
    /// Original immutable identity.
    pub source_digest: Digest,
    /// Structured text.
    pub markdown: String,
    /// Navigable source locations.
    pub outline: Vec<OutlineEntry>,
    /// Images, pages, tables, and other retained assets.
    pub assets: Vec<ConvertedAsset>,
    /// Extraction failures or quality limitations.
    pub warnings: Vec<Warning>,
}

/// Bounded worker execution backed by the selected conversion library.
pub trait Converter: Send + Sync {
    /// Convert with cancellation and resource bounds supplied by the worker supervisor.
    fn convert(&self, request: ConversionRequest) -> PortFuture<'_, ConversionResult>;
}
