//! Connector credentials, browser sessions, and installation identity are never inferred from content.
//!
//! A connector secret is generated by the store, returned once, and kept only as its
//! `secret_hash`. `create_connector` is unique on `MutationId`: a repeated id issues nothing and
//! reports the existing connector. The caller that resumes an abandoned attempt then calls
//! `rotate_connector_secret`, which invalidates the secret nobody received and returns a new one.

use okf_jawn_contract::access::{Connector, IssuedConnector, Principal};
use okf_jawn_contract::identity::{ConnectorId, MutationId, WorkspaceId};
use sha2::{Digest as _, Sha256};

use crate::ports::PortFuture;

/// Persistent local installation owner identity (local auth mode only).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InstallationIdentity {
    /// Stable subject for the local owner principal.
    pub subject: String,
    /// RFC 3339 creation time.
    pub created_at: String,
}

/// Authenticated browser session record without exposing the cookie secret.
#[derive(Debug, Clone)]
pub struct SessionRecord {
    /// Opaque session identity.
    pub session_id: String,
    /// Authenticated principal bound to the session.
    pub principal: Principal,
    /// RFC 3339 expiry.
    pub expires_at: String,
}

/// The scope of a local MCP connector to issue.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewConnector {
    /// Owner-chosen name identifying the client.
    pub label: String,
    /// Workspaces the connector may read.
    pub workspace_ids: Vec<WorkspaceId>,
    /// Also grant proposal creation; review and approval are never grantable.
    pub allow_propose: bool,
}

/// What `create_connector` found or made for one `MutationId`.
#[derive(Debug, Clone)]
pub enum ConnectorIssue {
    /// A new connector; this is the only time its secret is visible.
    Issued(IssuedConnector),
    /// A connector already exists for this `MutationId`; its secret cannot be shown again.
    Existing(Connector),
}

/// Connectors, sessions, and installation identity; storage owns the implementation.
pub trait CredentialStore: Send + Sync {
    /// Load or create the persistent local installation identity.
    fn installation_identity(&self) -> PortFuture<'_, InstallationIdentity>;
    /// Issue a local MCP connector credential.
    ///
    /// The store generates the secret from the operating system's random source, at least 32
    /// bytes, and keeps only `secret_hash` of it. Unique on `mutation_id`: a repeated id issues
    /// nothing and returns `ConnectorIssue::Existing`.
    fn create_connector(
        &self,
        mutation_id: MutationId,
        connector: NewConnector,
    ) -> PortFuture<'_, ConnectorIssue>;
    /// Replace a connector's secret; the previous secret stops authenticating at once.
    fn rotate_connector_secret(&self, connector: ConnectorId) -> PortFuture<'_, IssuedConnector>;
    /// List connector metadata without secrets, newest first.
    fn list_connectors(&self, include_revoked: bool) -> PortFuture<'_, Vec<Connector>>;
    /// Revoke a connector immediately; repeating it changes nothing.
    fn revoke_connector(&self, connector: ConnectorId) -> PortFuture<'_, Connector>;
    /// Resolve `secret_hash` of a presented secret to its connector when it is not revoked.
    fn lookup_connector(&self, hash: [u8; 32]) -> PortFuture<'_, Option<Connector>>;
    /// Persist a browser session after authentication.
    fn insert_session(&self, session: SessionRecord) -> PortFuture<'_, SessionRecord>;
    /// Resolve a session by opaque identity when unexpired.
    fn get_session<'a>(&'a self, session_id: &'a str) -> PortFuture<'a, Option<SessionRecord>>;
    /// Invalidate a browser session.
    fn revoke_session<'a>(&'a self, session_id: &'a str) -> PortFuture<'a, ()>;
}

/// The only form in which a connector secret is stored or looked up: SHA-256 of its bytes.
///
/// The store calls this when it persists a secret; the authenticating caller calls it before
/// `CredentialStore::lookup_connector`. A secret is long and random, so no salt is needed.
#[must_use]
pub fn secret_hash(secret: &str) -> [u8; 32] {
    Sha256::digest(secret.as_bytes()).into()
}
